/*----- PROTECTED REGION ID(PhyMotionControl.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        PhyMotionControl.cpp
//
// description : C++ source for the PhyMotionControl class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               PhyMotionControl are implemented in this file.
//
// project :     PhyMotionControl
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// GNU GPL (c) Kirill Pshenichnyi 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <PhyMotionControl.h>
#include <PhyMotionControlClass.h>

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl.cpp

/**
 *  PhyMotionControl class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  SendCMD       |  send_cmd
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//================================================================

namespace PhyMotionControl_ns
{
/*----- PROTECTED REGION ID(PhyMotionControl::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::PhyMotionControl()
 *	Description : Constructors for a Tango device
 *                implementing the classPhyMotionControl
 */
//--------------------------------------------------------
PhyMotionControl::PhyMotionControl(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(PhyMotionControl::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::constructor_1
}
//--------------------------------------------------------
PhyMotionControl::PhyMotionControl(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(PhyMotionControl::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::constructor_2
}
//--------------------------------------------------------
PhyMotionControl::PhyMotionControl(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(PhyMotionControl::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void PhyMotionControl::delete_device()
{
	DEBUG_STREAM << "PhyMotionControl::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(PhyMotionControl::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::delete_device
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void PhyMotionControl::init_device()
{
	DEBUG_STREAM << "PhyMotionControl::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(PhyMotionControl::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	/*----- PROTECTED REGION ID(PhyMotionControl::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::init_device
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void PhyMotionControl::get_device_property()
{
	/*----- PROTECTED REGION ID(PhyMotionControl::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("ip_addr"));
	dev_prop.push_back(Tango::DbDatum("tcp_port"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on PhyMotionControlClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		PhyMotionControlClass	*ds_class =
			(static_cast<PhyMotionControlClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize ip_addr from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  ip_addr;
		else {
			//	Try to initialize ip_addr from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  ip_addr;
		}
		//	And try to extract ip_addr value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  ip_addr;

		//	Try to initialize tcp_port from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  tcp_port;
		else {
			//	Try to initialize tcp_port from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  tcp_port;
		}
		//	And try to extract tcp_port value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  tcp_port;

	}

	/*----- PROTECTED REGION ID(PhyMotionControl::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void PhyMotionControl::always_executed_hook()
{
	DEBUG_STREAM << "PhyMotionControl::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(PhyMotionControl::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void PhyMotionControl::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "PhyMotionControl::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(PhyMotionControl::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::read_attr_hardware
}


//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void PhyMotionControl::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(PhyMotionControl::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command SendCMD related method
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevString PhyMotionControl::send_cmd(Tango::DevString argin)
{
	Tango::DevString argout;
	DEBUG_STREAM << "PhyMotionControl::SendCMD()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(PhyMotionControl::send_cmd) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::send_cmd
	return argout;
}
//--------------------------------------------------------
/**
 *	Method      : PhyMotionControl::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void PhyMotionControl::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(PhyMotionControl::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::add_dynamic_commands
}

/*----- PROTECTED REGION ID(PhyMotionControl::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::namespace_ending
} //	namespace
