/*----- PROTECTED REGION ID(PhyMotionControl.h) ENABLED START -----*/
//=============================================================================
//
// file :        PhyMotionControl.h
//
// description : Include file for the PhyMotionControl class
//
// project :     PhyMotionControl
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// GNU GPL (c) Kirill Pshenichnyi 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef PhyMotionControl_H
#define PhyMotionControl_H

#include <tango.h>

#include "TCPConnection.h"

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl.h

/**
 *  PhyMotionControl class description:
 *    
 */

namespace PhyMotionControl_ns
{
/*----- PROTECTED REGION ID(PhyMotionControl::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::Additional Class Declarations

class PhyMotionControl : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(PhyMotionControl::Data Members) ENABLED START -----*/

private:
    TCP_Connection::TCPConnection *tcp_connection;

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::Data Members

//	Device property data members
public:
	//	ip_addr:	Just IP addr for TCP connection to PhyMOTION device
	string	ip_addr;
	//	tcp_port:	TCP port for connection to PhyMOTION device
	Tango::DevShort	tcp_port;


//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	PhyMotionControl(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	PhyMotionControl(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	PhyMotionControl(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~PhyMotionControl() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : PhyMotionControl::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);


	//--------------------------------------------------------
	/**
	 *	Method      : PhyMotionControl::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command SendCMD related method
	 *	Description: 
	 *
	 *	@param argin 
	 *	@returns 
	 */
	virtual Tango::DevString send_cmd(Tango::DevString argin);
	virtual bool is_SendCMD_allowed(const CORBA::Any &any);
	/**
	 *	Command OpenConnection related method
	 *	Description: 
	 *
	 */
	virtual void open_connection();
	virtual bool is_OpenConnection_allowed(const CORBA::Any &any);
	/**
	 *	Command CloseConnection related method
	 *	Description: 
	 *
	 */
	virtual void close_connection();
	virtual bool is_CloseConnection_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : PhyMotionControl::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(PhyMotionControl::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::Additional Method prototypes
};

/*----- PROTECTED REGION ID(PhyMotionControl::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	PhyMotionControl::Additional Classes Definitions

}	//	End of namespace

#endif   //	PhyMotionControl_H
