/*----- PROTECTED REGION ID(PhyMotionControlClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        PhyMotionControlClass.h
//
// description : Include for the PhyMotionControl root class.
//               This class is the singleton class for
//                the PhyMotionControl device class.
//               It contains all properties and methods which the 
//               PhyMotionControl requires only once e.g. the commands.
//
// project :     PhyMotionControl
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// GNU GPL (c) Kirill Pshenichnyi 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef PhyMotionControlClass_H
#define PhyMotionControlClass_H

#include <tango.h>
#include <PhyMotionControl.h>


/*----- PROTECTED REGION END -----*/	//	PhyMotionControlClass.h


namespace PhyMotionControl_ns
{
/*----- PROTECTED REGION ID(PhyMotionControlClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	PhyMotionControlClass::classes for dynamic creation

//=========================================
//	Define classes for commands
//=========================================
//	Command SendCMD class definition
class SendCMDClass : public Tango::Command
{
public:
	SendCMDClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SendCMDClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SendCMDClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PhyMotionControl *>(dev))->is_SendCMD_allowed(any);}
};

//	Command OpenConnection class definition
class OpenConnectionClass : public Tango::Command
{
public:
	OpenConnectionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OpenConnectionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OpenConnectionClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PhyMotionControl *>(dev))->is_OpenConnection_allowed(any);}
};

//	Command CloseConnection class definition
class CloseConnectionClass : public Tango::Command
{
public:
	CloseConnectionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	CloseConnectionClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~CloseConnectionClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PhyMotionControl *>(dev))->is_CloseConnection_allowed(any);}
};

//	Command ResetDevice class definition
class ResetDeviceClass : public Tango::Command
{
public:
	ResetDeviceClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetDeviceClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetDeviceClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PhyMotionControl *>(dev))->is_ResetDevice_allowed(any);}
};

//	Command ResetStatus class definition
class ResetStatusClass : public Tango::Command
{
public:
	ResetStatusClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetStatusClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetStatusClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<PhyMotionControl *>(dev))->is_ResetStatus_allowed(any);}
};


/**
 *	The PhyMotionControlClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  PhyMotionControlClass : public Tango::DeviceClass
#else
class PhyMotionControlClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(PhyMotionControlClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionControlClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static PhyMotionControlClass *init(const char *);
		static PhyMotionControlClass *instance();
		~PhyMotionControlClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		PhyMotionControlClass(string &);
		static PhyMotionControlClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	PhyMotionControl_H
