/*----- PROTECTED REGION ID(MLZFormatDigitalOutput.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        MLZFormatDigitalOutput.cpp
//
// description : C++ source for the MLZFormatDigitalOutput class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               MLZFormatDigitalOutput are implemented in this file.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Pshenichnyi Kirill 2020 PNPI St.Petersburg
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <MLZFormatDigitalOutput.h>
#include <MLZFormatDigitalOutputClass.h>

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput.cpp

/**
 *  MLZFormatDigitalOutput class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name   |  Method name
//================================================================
//  State          |  Inherited (no method)
//  Status         |  Inherited (no method)
//  GetProperties  |  get_properties
//  SetProperties  |  set_properties
//  On             |  on
//  Off            |  off
//  Reset          |  reset
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  value    |  Tango::DevULong64	Scalar
//  version  |  Tango::DevString	Scalar
//================================================================

namespace MLZFormatDigitalOutput_ns
{
/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::MLZFormatDigitalOutput()
 *	Description : Constructors for a Tango device
 *                implementing the classMLZFormatDigitalOutput
 */
//--------------------------------------------------------
MLZFormatDigitalOutput::MLZFormatDigitalOutput(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::constructor_1
}
//--------------------------------------------------------
MLZFormatDigitalOutput::MLZFormatDigitalOutput(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::constructor_2
}
//--------------------------------------------------------
MLZFormatDigitalOutput::MLZFormatDigitalOutput(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::delete_device()
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::delete_device
	delete[] attr_value_read;
	delete[] attr_version_read;
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::init_device()
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_value_read = new Tango::DevULong64[1];
	attr_version_read = new Tango::DevString[1];
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::init_device) ENABLED START -----*/
	
	device_proxy_diom = new Tango::DeviceProxy(source_device);

	device_state = Tango::ON;
	device_status = "ok";
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::init_device
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::get_device_property()
{
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("source_device"));
	dev_prop.push_back(Tango::DbDatum("bits"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on MLZFormatDigitalOutputClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		MLZFormatDigitalOutputClass	*ds_class =
			(static_cast<MLZFormatDigitalOutputClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize source_device from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  source_device;
		else {
			//	Try to initialize source_device from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  source_device;
		}
		//	And try to extract source_device value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  source_device;

		//	Try to initialize bits from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  bits;
		else {
			//	Try to initialize bits from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  bits;
		}
		//	And try to extract bits value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  bits;

	}

	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::always_executed_hook()
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute value related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::read_value(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::read_value(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::read_value) ENABLED START -----*/

	Tango::DevUShort value;
	device_proxy_diom->read_attribute("outputs") >> value;
	*attr_value_read = value;

	attr.set_value(attr_value_read);
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::read_value
}
//--------------------------------------------------------
/**
 *	Write attribute value related method
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::write_value(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::write_value(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevULong64	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::write_value) ENABLED START -----*/

	Tango::DevUShort value = w_val;

    Tango::DeviceAttribute a_value("outputs",value);
    device_proxy_diom->write_attribute(a_value);
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::write_value
}
//--------------------------------------------------------
/**
 *	Read attribute version related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::read_version(Tango::Attribute &attr)
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::read_version(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::read_version) ENABLED START -----*/
	*attr_version_read = "module v1.0";
	attr.set_value(attr_version_read);
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::read_version
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command GetProperties related method
 *	Description: 
 *
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevVarStringArray *MLZFormatDigitalOutput::get_properties()
{
	Tango::DevVarStringArray *argout;
	DEBUG_STREAM << "MLZFormatDigitalOutput::GetProperties()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::get_properties) ENABLED START -----*/

    const short int num_prop = 1;
    Tango::DevVarStringArray *prop_list = new Tango::DevVarStringArray(2*num_prop);
    prop_list->length(2*num_prop);
    (*prop_list)[0] = "bits";
    (*prop_list)[1] = (std::to_string(bits)).c_str();
    argout = prop_list;
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::get_properties
	return argout;
}
//--------------------------------------------------------
/**
 *	Command SetProperties related method
 *	Description: 
 *
 *	@param argin 
 *	@returns 
 */
//--------------------------------------------------------
Tango::DevBoolean MLZFormatDigitalOutput::set_properties(const Tango::DevVarStringArray *argin)
{
	Tango::DevBoolean argout;
	DEBUG_STREAM << "MLZFormatDigitalOutput::SetProperties()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::set_properties) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::set_properties
	return argout;
}
//--------------------------------------------------------
/**
 *	Command On related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::on()
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::On()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::on) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::on
}
//--------------------------------------------------------
/**
 *	Command Off related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::off()
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::Off()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::off) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::off
}
//--------------------------------------------------------
/**
 *	Command Reset related method
 *	Description: 
 *
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::reset()
{
	DEBUG_STREAM << "MLZFormatDigitalOutput::Reset()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::reset) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::reset
}
//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void MLZFormatDigitalOutput::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::add_dynamic_commands
}

/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::namespace_ending
} //	namespace
