/*----- PROTECTED REGION ID(MLZFormatDigitalOutputStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        MLZFormatDigitalOutputStateMachine.cpp
//
// description : State machine file for the MLZFormatDigitalOutput class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Pshenichnyi Kirill 2020 PNPI St.Petersburg
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <MLZFormatDigitalOutput.h>

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::MLZFormatDigitalOutputStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace MLZFormatDigitalOutput_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::is_value_allowed()
 *	Description : Execution allowed for value attribute
 */
//--------------------------------------------------------
bool MLZFormatDigitalOutput::is_value_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for value attribute in Write access.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::valueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::valueStateAllowed_WRITE

	//	Not any excluded states for value attribute in read access.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::valueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::valueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::is_version_allowed()
 *	Description : Execution allowed for version attribute
 */
//--------------------------------------------------------
bool MLZFormatDigitalOutput::is_version_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for version attribute in read access.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::versionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::versionStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::is_GetProperties_allowed()
 *	Description : Execution allowed for GetProperties attribute
 */
//--------------------------------------------------------
bool MLZFormatDigitalOutput::is_GetProperties_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetProperties command.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::GetPropertiesStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::GetPropertiesStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::is_SetProperties_allowed()
 *	Description : Execution allowed for SetProperties attribute
 */
//--------------------------------------------------------
bool MLZFormatDigitalOutput::is_SetProperties_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetProperties command.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::SetPropertiesStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::SetPropertiesStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool MLZFormatDigitalOutput::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool MLZFormatDigitalOutput::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::OffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : MLZFormatDigitalOutput::is_Reset_allowed()
 *	Description : Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool MLZFormatDigitalOutput::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::ResetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::ResetStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(MLZFormatDigitalOutput::MLZFormatDigitalOutputStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalOutput::MLZFormatDigitalOutputStateAllowed.AdditionalMethods

}	//	End of namespace
