/*----- PROTECTED REGION ID(AxisClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        AxisClass.h
//
// description : Include for the Axis root class.
//               This class is the singleton class for
//                the Axis device class.
//               It contains all properties and methods which the 
//               Axis requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Abstract class for axis on TEX for PhyMotionMotor class
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef AxisClass_H
#define AxisClass_H

#include <tango.h>
#include <Axis.h>


/*----- PROTECTED REGION END -----*/	//	AxisClass.h


namespace Axis_ns
{
/*----- PROTECTED REGION ID(AxisClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	AxisClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute position class definition
class positionAttrib: public Tango::Attr
{
public:
	positionAttrib():Attr("position",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~positionAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Axis *>(dev))->read_position(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<Axis *>(dev))->write_position(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Axis *>(dev))->is_position_allowed(ty);}
};

//	Attribute limit_switch_p class definition
class limit_switch_pAttrib: public Tango::Attr
{
public:
	limit_switch_pAttrib():Attr("limit_switch_p",
			Tango::DEV_BOOLEAN, Tango::READ) {};
	~limit_switch_pAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Axis *>(dev))->read_limit_switch_p(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Axis *>(dev))->is_limit_switch_p_allowed(ty);}
};

//	Attribute limit_switch_c class definition
class limit_switch_cAttrib: public Tango::Attr
{
public:
	limit_switch_cAttrib():Attr("limit_switch_c",
			Tango::DEV_BOOLEAN, Tango::READ) {};
	~limit_switch_cAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Axis *>(dev))->read_limit_switch_c(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Axis *>(dev))->is_limit_switch_c_allowed(ty);}
};

//	Attribute limit_switch_m class definition
class limit_switch_mAttrib: public Tango::Attr
{
public:
	limit_switch_mAttrib():Attr("limit_switch_m",
			Tango::DEV_BOOLEAN, Tango::READ) {};
	~limit_switch_mAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Axis *>(dev))->read_limit_switch_m(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Axis *>(dev))->is_limit_switch_m_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command Stop class definition
class StopClass : public Tango::Command
{
public:
	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<Axis *>(dev))->is_Stop_allowed(any);}
};


/**
 *	The AxisClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  AxisClass : public Tango::DeviceClass
#else
class AxisClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(AxisClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	AxisClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static AxisClass *init(const char *);
		static AxisClass *instance();
		~AxisClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		AxisClass(string &);
		static AxisClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	Axis_H
