/*----- PROTECTED REGION ID(PhyMotionMotorClass.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        PhyMotionMotorClass.cpp
//
// description : C++ source for the PhyMotionMotorClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the PhyMotionMotor once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Pshenichnyi Kirill PNPI 2019
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <PhyMotionMotorClass.h>

/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass.cpp

//-------------------------------------------------------------------
/**
 *	Create PhyMotionMotorClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_PhyMotionMotor_class(const char *name) {
		return PhyMotionMotor_ns::PhyMotionMotorClass::init(name);
	}
}

namespace PhyMotionMotor_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
PhyMotionMotorClass *PhyMotionMotorClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		PhyMotionMotorClass::PhyMotionMotorClass(string &s)
 * description : 	constructor for the PhyMotionMotorClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
PhyMotionMotorClass::PhyMotionMotorClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering PhyMotionMotorClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(PhyMotionMotorClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::constructor

	cout2 << "Leaving PhyMotionMotorClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		PhyMotionMotorClass::~PhyMotionMotorClass()
 * description : 	destructor for the PhyMotionMotorClass
 */
//--------------------------------------------------------
PhyMotionMotorClass::~PhyMotionMotorClass()
{
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		PhyMotionMotorClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
PhyMotionMotorClass *PhyMotionMotorClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new PhyMotionMotorClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		PhyMotionMotorClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
PhyMotionMotorClass *PhyMotionMotorClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		StopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopClass::execute(): arrived" << endl;
	((static_cast<PhyMotionMotor *>(device))->stop());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetStatusClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetStatusClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetStatusClass::execute(): arrived" << endl;
	((static_cast<PhyMotionMotor *>(device))->reset_status());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetMechanicalZeroCounterClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetMechanicalZeroCounterClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetMechanicalZeroCounterClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PhyMotionMotor *>(device))->set_mechanical_zero_counter(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		goToClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *goToClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "goToClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PhyMotionMotor *>(device))->go_to(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		setAccelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *setAccelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "setAccelClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PhyMotionMotor *>(device))->set_accel(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		setDecelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *setDecelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "setDecelClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PhyMotionMotor *>(device))->set_decel(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		setSpeedClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *setSpeedClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "setSpeedClass::execute(): arrived" << endl;
	Tango::DevDouble argin;
	extract(in_any, argin);
	((static_cast<PhyMotionMotor *>(device))->set_speed(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		getMZCClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *getMZCClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "getMZCClass::execute(): arrived" << endl;
	return insert((static_cast<PhyMotionMotor *>(device))->get_mzc());
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum PhyMotionMotorClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum PhyMotionMotorClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum PhyMotionMotorClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void PhyMotionMotorClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "control_device";
	prop_desc = "just path to device of PhyMotionControl";
	prop_def  = "device/PhyMOTION/control";
	vect_data.clear();
	vect_data.push_back("device/PhyMOTION/control");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "module";
	prop_desc = "number of module";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "axis";
	prop_desc = "number of axis";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "address";
	prop_desc = "just address: 0-9,A-F or @ - for all";
	prop_def  = "@";
	vect_data.clear();
	vect_data.push_back("@");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P01";
	prop_desc = "Type of movement (free run, relative/absolute, reference run)\n0 = Rotation movement (ignoring limit switches)\n1 = Hardware limit switches are monitored\n2 = Software limit switches are monitored\n3 = Hardware and sofrware limit swtiches are monitored";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P02";
	prop_desc = "Measuring units of movement: only used for displaying\n1 = step\n2 = mm\n3 = inch\n4 = degree";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P03";
	prop_desc = "Conversion factor for the thread\n\nCf = therad/Number_of_steps_perrevolution";
	prop_def  = "1.0";
	vect_data.clear();
	vect_data.push_back("1.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P04";
	prop_desc = "Start/Stop frequency";
	prop_def  = "400.0";
	vect_data.clear();
	vect_data.push_back("400.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P07";
	prop_desc = "Emergency stop ramp\nInput for \nI1AM0x: in 4000 Hz/s steps\nI4XM01: in 1Hz/steps";
	prop_def  = "100000";
	vect_data.clear();
	vect_data.push_back("100000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P08";
	prop_desc = "f_max MØP\nRun frequency during initilizing (referecing)\nEnter in Hz (integer value)\nI1AM0x: 40 000 maximum\nI4XM01: 4 000 000 maximum";
	prop_def  = "4000";
	vect_data.clear();
	vect_data.push_back("4000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P09";
	prop_desc = "Ramp MØP\nRamp during initializing, associated to parameter P08\nInput for\nI1AM0x: in 4000 Hz/s steps\nI4XM01: in 1 Hz/s steps";
	prop_def  = "4000";
	vect_data.clear();
	vect_data.push_back("4000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P10";
	prop_desc = "f_min MØP Run frequency for leaving the limit switch range\n\nEnter in Hz";
	prop_def  = "400";
	vect_data.clear();
	vect_data.push_back("400");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P11";
	prop_desc = "MØP offset for limit switch direction \n+ (away from ``LIMIT+`` switch, towards ``LIMIT?`` switch)\nDistance between reference point MØP and limit switch \nactivation\nUnit: is defined in parameter P02\nP11>=0";
	prop_def  = "0.0";
	vect_data.clear();
	vect_data.push_back("0.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P12";
	prop_desc = "MØP offset for limit switch direction ?(away from \n``LIMIT?`` switch, towards ``LIMIT+`` switch)\nDistance between reference point MØP and limit switch\nactivation\nUnit: is defined in parameter P02\nP12>=0";
	prop_def  = "0.0";
	vect_data.clear();
	vect_data.push_back("0.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P13";
	prop_desc = "Recovery time MØP\nTime lapse during initialization\nEnter in msec";
	prop_def  = "20";
	vect_data.clear();
	vect_data.push_back("20");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P14";
	prop_desc = "Run frequency (max) during program operation\nEnter in Hz (integer value)  \nI1AM0x: 40 000 maximum\nI4XM01: 4 000 000 maximum";
	prop_def  = "4000";
	vect_data.clear();
	vect_data.push_back("4000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P15";
	prop_desc = "Ramp for run frequency (P14)\nInput for\nI1AM0x: in 4000 Hz/s steps\nI4XM01: in 1 Hz/s steps";
	prop_def  = "100";
	vect_data.clear();
	vect_data.push_back("100");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P16";
	prop_desc = "Recovery time position\nTime lapse after positioning\nInput in msec";
	prop_def  = "20";
	vect_data.clear();
	vect_data.push_back("20");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P17";
	prop_desc = "Boost (current is defined in P42)\n0 = off\n1 = on during motor run\n2 = on during acceleration and deceleration ramp";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P23";
	prop_desc = "Software Limit Switch (Axial limitation  pos. direction +)\nIf the distance is reached, the run in + direction is aborted.\n0 = no limitation";
	prop_def  = "0.0";
	vect_data.clear();
	vect_data.push_back("0.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P24";
	prop_desc = "Software Limit Switch (Axial limitation  neg. direction -)\nIf the distance is reached, the run in - direction is aborted.  \n0 = no limitation";
	prop_def  = "0.0";
	vect_data.clear();
	vect_data.push_back("0.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P25";
	prop_desc = "Compensation for play\nIndicates the distance,the target position in the selected\ndirection is passed over and afterwards is started in\nreverse direction.\n0 = no compensation for play";
	prop_def  = "0.0";
	vect_data.clear();
	vect_data.push_back("0.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P26";
	prop_desc = "The data transfer rate is set by P26 (ONLY for SSIencoder),   \nby which the encoder is read. The transferrate is dependent\n on the length of the cable by whichthe encoder is connected to the device. The shorter the cable, the encoder \ncan more quickly be read.\nData transfer rate 1 to 10 (= 100 to 1000 kHz)";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P27";
	prop_desc = "Limit switch type";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P28";
	prop_desc = "Axis power option\n0 = Power stage is deactivated after power on\n1 = Power stage is activated after power on";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P30";
	prop_desc = "For I4XM01 only!\nFrequency band setting \n0 = manual\n1 = automatic";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P31";
	prop_desc = "For I4XM01 only!\nFrequency and ramp predivider (only if P30 = 0, manual)";
	prop_def  = "3";
	vect_data.clear();
	vect_data.push_back("3");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P32";
	prop_desc = "Positioning ramp shape\n0 = s-shape\n1 = linear ramp\nRemark: The s-shape ramp can be modified with P33 parameter.";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P33";
	prop_desc = "Arc value setting for s-sharpe ramp\nValues:\nOMC: 1 to 8191\nTMC: 1:23767";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P34";
	prop_desc = "Encoder type";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P35";
	prop_desc = "Encoder resolution for SSI and EnDat encoder\nEnter max. encoder resolution in Bit (max 48 Bit)";
	prop_def  = "10";
	vect_data.clear();
	vect_data.push_back("10");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P36";
	prop_desc = "Encoder function	\n0 - counter\n1 - counter + SFI";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P37";
	prop_desc = "Encoder tolerance for SFI";
	prop_def  = "0.0";
	vect_data.clear();
	vect_data.push_back("0.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P38";
	prop_desc = "Encoder preferential direction of rotation\n0 = + (positive)\n1 = - (negative)";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P39";
	prop_desc = "Encoder conversion factor\n\nthread/encoder_step_prrevolution";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P40";
	prop_desc = "Stop current in 0.01 A";
	prop_def  = "2";
	vect_data.clear();
	vect_data.push_back("2");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P41";
	prop_desc = "Run current in 0.01 A";
	prop_def  = "6";
	vect_data.clear();
	vect_data.push_back("6");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P42";
	prop_desc = "Boost current in 0.01 A";
	prop_def  = "10";
	vect_data.clear();
	vect_data.push_back("10");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P43";
	prop_desc = "Current hold time in msec";
	prop_def  = "20";
	vect_data.clear();
	vect_data.push_back("20");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P44";
	prop_desc = "for I4XM01 only!\nOrigin of the control pulses for the axis";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P45";
	prop_desc = "Step resolution 0 .. 13 = [1, .. 1/512]\n    [ 0,   1,    2,       3,    4,    5,     6,     7,       8,]\n= [1/1, 1/2, 1/2.5, 1/4, 1/5, 1/8, 1/10, 1/16, 1/20]\n    [9,      10     11,      12,      13     ]\n= [1/32, 1/64, 1/128, 1/256, 1/512]\nFor I1AM step resolution from 1/1 to 1/128 step";
	prop_def  = "3";
	vect_data.clear();
	vect_data.push_back("3");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P50";
	prop_desc = "Devider for control pulses, only I4XM01\npulses= 1/(n+1):\nexample for pulses = 1/4 = 1/(3+1), n=3\nn = 0 .. 5";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P51";
	prop_desc = "Pulses width: (n+1)*100 ns only I4XM01\nExample for 2000 ns = (19+1)*100 ns\nn=0 .. 255";
	prop_def  = "19";
	vect_data.clear();
	vect_data.push_back("19");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P53";
	prop_desc = "Power stage monitoring\n0 = off\n1 = on";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P55";
	prop_desc = "Motor temperature warning in 1/10 C";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P56";
	prop_desc = "Motor temperature shut-off in 1/10 C";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P57";
	prop_desc = "Resolver voltage\nn = 3 .. 10 (Volt)";
	prop_def  = "3";
	vect_data.clear();
	vect_data.push_back("3");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "P58";
	prop_desc = "Resolver ratio (ratio of primary to secondary winding)\n[0,    1,    2,    3, 4]\n[1/8, 1/4, 1/2, 1, 2]";
	prop_def  = "2";
	vect_data.clear();
	vect_data.push_back("2");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void PhyMotionMotorClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void PhyMotionMotorClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new PhyMotionMotor(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		PhyMotionMotor *dev = static_cast<PhyMotionMotor *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(PhyMotionMotorClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void PhyMotionMotorClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::attribute_factory_before
	//	Attribute : position
	positionAttrib	*position = new positionAttrib();
	Tango::UserDefaultAttrProp	position_prop;
	position_prop.set_description("For read - this is P20 parameter - mechanical zero counter");
	position_prop.set_label("Position");
	//	unit	not set for position
	//	standard_unit	not set for position
	//	display_unit	not set for position
	//	format	not set for position
	//	max_value	not set for position
	//	min_value	not set for position
	//	max_alarm	not set for position
	//	min_alarm	not set for position
	//	max_warning	not set for position
	//	min_warning	not set for position
	//	delta_t	not set for position
	//	delta_val	not set for position
	
	position->set_default_properties(position_prop);
	//	Not Polled
	position->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(position);

	//	Attribute : absolute_counter
	absolute_counterAttrib	*absolute_counter = new absolute_counterAttrib();
	Tango::UserDefaultAttrProp	absolute_counter_prop;
	absolute_counter_prop.set_description("P21 Reading");
	absolute_counter_prop.set_label("Absolute counter");
	//	unit	not set for absolute_counter
	//	standard_unit	not set for absolute_counter
	//	display_unit	not set for absolute_counter
	//	format	not set for absolute_counter
	//	max_value	not set for absolute_counter
	//	min_value	not set for absolute_counter
	//	max_alarm	not set for absolute_counter
	//	min_alarm	not set for absolute_counter
	//	max_warning	not set for absolute_counter
	//	min_warning	not set for absolute_counter
	//	delta_t	not set for absolute_counter
	//	delta_val	not set for absolute_counter
	
	absolute_counter->set_default_properties(absolute_counter_prop);
	//	Not Polled
	absolute_counter->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(absolute_counter);

	//	Attribute : axis_status
	axis_statusAttrib	*axis_status = new axis_statusAttrib();
	Tango::UserDefaultAttrProp	axis_status_prop;
	//	description	not set for axis_status
	axis_status_prop.set_label("Axis status");
	//	unit	not set for axis_status
	//	standard_unit	not set for axis_status
	//	display_unit	not set for axis_status
	axis_status_prop.set_format("0x%x");
	//	max_value	not set for axis_status
	//	min_value	not set for axis_status
	//	max_alarm	not set for axis_status
	//	min_alarm	not set for axis_status
	//	max_warning	not set for axis_status
	//	min_warning	not set for axis_status
	//	delta_t	not set for axis_status
	//	delta_val	not set for axis_status
	
	axis_status->set_default_properties(axis_status_prop);
	//	Not Polled
	axis_status->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(axis_status);

	//	Attribute : activate
	activateAttrib	*activate = new activateAttrib();
	Tango::UserDefaultAttrProp	activate_prop;
	activate_prop.set_description("Enable current in motor");
	activate_prop.set_label("Activate");
	//	unit	not set for activate
	//	standard_unit	not set for activate
	//	display_unit	not set for activate
	//	format	not set for activate
	//	max_value	not set for activate
	//	min_value	not set for activate
	//	max_alarm	not set for activate
	//	min_alarm	not set for activate
	//	max_warning	not set for activate
	//	min_warning	not set for activate
	//	delta_t	not set for activate
	//	delta_val	not set for activate
	
	activate->set_default_properties(activate_prop);
	//	Not Polled
	activate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(activate);

	//	Attribute : power_stage_temperature
	power_stage_temperatureAttrib	*power_stage_temperature = new power_stage_temperatureAttrib();
	Tango::UserDefaultAttrProp	power_stage_temperature_prop;
	power_stage_temperature_prop.set_description("Read parameter P49");
	power_stage_temperature_prop.set_label("Power stage temperature");
	power_stage_temperature_prop.set_unit("C");
	//	standard_unit	not set for power_stage_temperature
	power_stage_temperature_prop.set_display_unit("C");
	//	format	not set for power_stage_temperature
	//	max_value	not set for power_stage_temperature
	//	min_value	not set for power_stage_temperature
	//	max_alarm	not set for power_stage_temperature
	//	min_alarm	not set for power_stage_temperature
	//	max_warning	not set for power_stage_temperature
	//	min_warning	not set for power_stage_temperature
	//	delta_t	not set for power_stage_temperature
	//	delta_val	not set for power_stage_temperature
	
	power_stage_temperature->set_default_properties(power_stage_temperature_prop);
	//	Not Polled
	power_stage_temperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(power_stage_temperature);

	//	Attribute : motor_temperature
	motor_temperatureAttrib	*motor_temperature = new motor_temperatureAttrib();
	Tango::UserDefaultAttrProp	motor_temperature_prop;
	motor_temperature_prop.set_description("read parameter P54");
	motor_temperature_prop.set_label("Motor temperature");
	motor_temperature_prop.set_unit("C");
	//	standard_unit	not set for motor_temperature
	motor_temperature_prop.set_display_unit("C");
	//	format	not set for motor_temperature
	//	max_value	not set for motor_temperature
	//	min_value	not set for motor_temperature
	//	max_alarm	not set for motor_temperature
	//	min_alarm	not set for motor_temperature
	//	max_warning	not set for motor_temperature
	//	min_warning	not set for motor_temperature
	//	delta_t	not set for motor_temperature
	//	delta_val	not set for motor_temperature
	
	motor_temperature->set_default_properties(motor_temperature_prop);
	//	Not Polled
	motor_temperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(motor_temperature);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void PhyMotionMotorClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::pipe_factory_before
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void PhyMotionMotorClass::command_factory()
{
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::command_factory_before


	//	Command Stop
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);

	//	Command ResetStatus
	ResetStatusClass	*pResetStatusCmd =
		new ResetStatusClass("ResetStatus",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetStatusCmd);

	//	Command SetMechanicalZeroCounter
	SetMechanicalZeroCounterClass	*pSetMechanicalZeroCounterCmd =
		new SetMechanicalZeroCounterClass("SetMechanicalZeroCounter",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetMechanicalZeroCounterCmd);

	//	Command goTo
	goToClass	*pgoToCmd =
		new goToClass("goTo",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pgoToCmd);

	//	Command setAccel
	setAccelClass	*psetAccelCmd =
		new setAccelClass("setAccel",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(psetAccelCmd);

	//	Command setDecel
	setDecelClass	*psetDecelCmd =
		new setDecelClass("setDecel",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(psetDecelCmd);

	//	Command setSpeed
	setSpeedClass	*psetSpeedCmd =
		new setSpeedClass("setSpeed",
			Tango::DEV_DOUBLE, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(psetSpeedCmd);

	//	Command getMZC
	getMZCClass	*pgetMZCCmd =
		new getMZCClass("getMZC",
			Tango::DEV_VOID, Tango::DEV_DOUBLE,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pgetMZCCmd);

	/*----- PROTECTED REGION ID(PhyMotionMotorClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		PhyMotionMotorClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void PhyMotionMotorClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(PhyMotionMotorClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		PhyMotionMotorClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void PhyMotionMotorClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		PhyMotionMotor *dev = static_cast<PhyMotionMotor *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(PhyMotionMotorClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : PhyMotionMotorClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *PhyMotionMotorClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(PhyMotionMotorClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	PhyMotionMotorClass::Additional Methods
} //	namespace
