/*----- PROTECTED REGION ID(MLZFormatDigitalInput.h) ENABLED START -----*/
//=============================================================================
//
// file :        MLZFormatDigitalInput.h
//
// description : Include file for the MLZFormatDigitalInput class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// PNPI St.Petersburg
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef MLZFormatDigitalInput_H
#define MLZFormatDigitalInput_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalInput.h

/**
 *  MLZFormatDigitalInput class description:
 *    
 */

namespace MLZFormatDigitalInput_ns
{
/*----- PROTECTED REGION ID(MLZFormatDigitalInput::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalInput::Additional Class Declarations

class MLZFormatDigitalInput : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(MLZFormatDigitalInput::Data Members) ENABLED START -----*/

private:
    Tango::DeviceProxy *diom_device_proxy;

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalInput::Data Members

//	Device property data members
public:
	//	source_device:	
	string	source_device;
	//	bits:	
	Tango::DevUShort	bits;

//	Attribute data members
public:
	Tango::DevString	*attr_version_read;
	Tango::DevULong64	*attr_value_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	MLZFormatDigitalInput(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	MLZFormatDigitalInput(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	MLZFormatDigitalInput(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~MLZFormatDigitalInput() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : MLZFormatDigitalInput::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute version related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_version(Tango::Attribute &attr);
	virtual bool is_version_allowed(Tango::AttReqType type);
/**
 *	Attribute value related methods
 *	Description: 
 *
 *	Data type:	Tango::DevULong64
 *	Attr type:	Scalar
 */
	virtual void read_value(Tango::Attribute &attr);
	virtual bool is_value_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : MLZFormatDigitalInput::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command GetProperties related method
	 *	Description: 
	 *
	 *	@returns 
	 */
	virtual Tango::DevVarStringArray *get_properties();
	virtual bool is_GetProperties_allowed(const CORBA::Any &any);
	/**
	 *	Command SetProperties related method
	 *	Description: 
	 *
	 *	@param argin 
	 *	@returns 
	 */
	virtual Tango::DevBoolean set_properties(const Tango::DevVarStringArray *argin);
	virtual bool is_SetProperties_allowed(const CORBA::Any &any);
	/**
	 *	Command On related method
	 *	Description: 
	 *
	 */
	virtual void on();
	virtual bool is_On_allowed(const CORBA::Any &any);
	/**
	 *	Command Off related method
	 *	Description: 
	 *
	 */
	virtual void off();
	virtual bool is_Off_allowed(const CORBA::Any &any);
	/**
	 *	Command Reset related method
	 *	Description: 
	 *
	 */
	virtual void reset();
	virtual bool is_Reset_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : MLZFormatDigitalInput::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(MLZFormatDigitalInput::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalInput::Additional Method prototypes
};

/*----- PROTECTED REGION ID(MLZFormatDigitalInput::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	MLZFormatDigitalInput::Additional Classes Definitions

}	//	End of namespace

#endif   //	MLZFormatDigitalInput_H
